/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GoatHeaderAction {
        /**
          * @default '_self'
         */
        "badge": string;
        /**
          * @default {}
         */
        "configAria": any;
        /**
          * Hyperlink to navigate to on click.
         */
        "href": string;
        /**
          * Icon which will displayed on button. Possible values are icon names.
         */
        "icon": string;
        "setColor": (color: string) => Promise<void>;
        /**
          * IconButton size. Possible values are `"sm"`, `"md"`, `"lg"`, `"xl"`, `"xxl"`, `"none"`. Defaults to `"md"`.
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg' | 'xl' | 'xxl' | 'none';
        /**
          * Sets or retrieves the window or frame at which to target content.
          * @default '_self'
         */
        "target": string;
    }
    interface GoatHeaderBrand {
        /**
          * @default '#'
         */
        "href": string;
        "logo": string;
        "name": string;
        "setColor": (color: string) => Promise<void>;
        "subTitle": string;
    }
    /**
     * @label HTML Editor
     * @name html-editor
     * @description HTML Editor component is a WYSIWYG editor that allows users to edit HTML content.
     * @category Form Inputs
     * @tags input, form
     * @img /assets/img/html-editor.webp
     * @imgDark /assets/img/html-editor-dark.webp
     */
    interface GoatHtmlEditor {
        /**
          * Set the amount of time, in milliseconds, to wait to trigger the `onChange` event after each keystroke.
          * @default 250
         */
        "debounce": number;
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
          * @default false
         */
        "disabled": boolean;
        "getComponentId": () => Promise<string>;
        "layer"?: 'background' | '01' | '02';
        /**
          * @default 'on'
         */
        "lineNumbers": 'off' | 'on';
        /**
          * @default []
         */
        "mentions": { label: string; value: string }[];
        /**
          * @default 'contains'
         */
        "mentionsSearch": 'contains' | 'managed';
        /**
          * The input field name.
          * @default `pc-input-${this.gid}`
         */
        "name": string;
        /**
          * The input field placeholder.
         */
        "placeholder": string;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * If true, required icon is show. Defaults to `false`.
          * @default false
         */
        "required": boolean;
        /**
          * Sets blur on the native `input` in `pc-input`. Use this method instead of the global `input.blur()`.
         */
        "setBlur": () => Promise<void>;
        /**
          * Sets focus on the native `input` in `pc-input`. Use this method instead of the global `input.focus()`.
         */
        "setFocus": () => Promise<void>;
        /**
          * @default true
         */
        "showSuggestionCharacter": boolean;
        /**
          * @default true
         */
        "showToolbar": boolean;
        /**
          * @default '@'
         */
        "suggestionCharacter": string;
        /**
          * @default 'vs-light'
         */
        "theme": 'vs-light' | 'vs-dark';
        /**
          * The input field value.
         */
        "value": string;
    }
    /**
     * @label Canvas
     * @name canvas
     * @category Up coming
     * @description Canvas for drawing lines and shapes on.
     * @img /assets/img/canvas.webp
     */
    interface PcCanvas {
        /**
          * @default 1
         */
        "padding": number;
        /**
          * @default []
         */
        "shapes": any[];
        "viewbox"?: string;
        /**
          * @default 1
         */
        "zoom": number;
    }
    /**
     * @label Dropdown
     * @name dropdown
     * @description Enables native inputs to be used within a Form field.
     * @category Navigation
     * @subcategory Dropdown
     * @img /assets/img/dropdown.webp
     * @imgDark /assets/img/dropdown-dark.webp
     */
    interface PcDropdown {
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "managed": boolean;
        /**
          * @default false
         */
        "open": boolean;
        /**
          * @default 'bottom-start,top-start,bottom-end,top-end'
         */
        "placements": string;
        "setFocus": () => Promise<void>;
        /**
          * @default 'click'
         */
        "trigger": 'click' | 'hover' | 'manual';
    }
    /**
     * @label Dropdown Menu
     * @name dropdown-menu
     * @description The Dropdown Menu component is used to display a list of options.
     * @category Navigation
     * @subcategory Dropdown
     * @childComponent true
     */
    interface PcDropdownMenu {
        /**
          * Sets focus on first menu item. Use this method instead of the global `element.focus()`.
         */
        "setFocus": () => Promise<void>;
    }
    /**
     * @label Flow Designer
     * @name flow-designer
     * @category Up coming
     * @description Flow Designer is a component that allows users to create and edit flows.
     * @img /assets/img/flow-designer.webp
     */
    interface PcFlowDesigner {
        /**
          * @default 16
         */
        "blockSize": number;
        /**
          * @default []
         */
        "data": any[];
        /**
          * @default false
         */
        "disabled": boolean;
    }
    /**
     * @label Form Control
     * @name form-control
     * @description The Form Control component adds a label and caption for its child control.
     * @category Form Inputs
     * @tags form
     * @example <pc-form-control label='Full Name' required>
     * <pc-input type='text'></pc-input>
     * </pc-form-control>
     */
    interface PcFormControl {
        "helperText": string;
        /**
          * @default false
         */
        "inline": boolean;
        /**
          * @default false
         */
        "invalid": boolean;
        "invalidText": string;
        "label": string;
        /**
          * Whether the form control is required.
          * @default false
         */
        "required": boolean;
        /**
          * @default false
         */
        "skeleton": boolean;
        /**
          * @default false
         */
        "warn": boolean;
        "warnText": string;
    }
    /**
     * @label Header
     * @name header
     * @description Header component is used to display a header with a brand, navigation, and actions.
     * @category Navigation
     * @img /assets/img/header.webp
     * @imgDark /assets/img/header-dark.webp
     */
    interface PcHeader {
        /**
          * Defines the primary color of the header. This can be set to predefined color names to apply specific color themes.
          * @default 'black'
         */
        "color": | 'primary'
    | 'secondary'
    | 'success'
    | 'danger'
    | 'warning'
    | 'white'
    | 'black'
    | string;
        /**
          * Color variant for dark mode, applicable when [data-theme="dark"] is set.
         */
        "darkModeColor"?: | 'primary'
    | 'secondary'
    | 'success'
    | 'danger'
    | 'warning'
    | 'white'
    | 'black'
    | string;
        /**
          * @default false
         */
        "float": boolean;
    }
    /**
     * @label Input
     * @name input
     * @description Enables native inputs to be used within a Form field.
     * @category Form Inputs
     * @tags input, form
     * @example <pc-input placeholder="Enter your name"></pc-input>
     */
    interface PcInput {
        /**
          * Indicates whether the value of the control can be automatically completed by the browser.
          * @default 'off'
         */
        "autocomplete": 'on' | 'off';
        /**
          * @default {}
         */
        "configAria": any;
        /**
          * Set the amount of time, in milliseconds, to wait to trigger the `goatChange` event after each keystroke.
          * @default 300
         */
        "debounce": number;
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
          * @default false
         */
        "disabled": boolean;
        "getComponentId": () => Promise<string>;
        "helperText": string;
        /**
          * @default false
         */
        "inline": boolean;
        /**
          * @default false
         */
        "invalid": boolean;
        "invalidText": string;
        "label": string;
        /**
          * The input field name.
          * @default `pc-input-${this.gid}`
         */
        "name": string;
        /**
          * The input field placeholder.
         */
        "placeholder": string;
        /**
          * If true, the user read the value cannot modify it. Defaults to `false`.
          * @default false
         */
        "readonly": boolean;
        /**
          * If true, required icon is show. Defaults to `false`.
          * @default false
         */
        "required": boolean;
        /**
          * Sets blur on the native `input` in `pc-input`. Use this method instead of the global `input.blur()`.
         */
        "setBlur": () => Promise<void>;
        /**
          * Sets focus on the native `input` in `pc-input`. Use this method instead of the global `input.focus()`.
         */
        "setFocus": () => Promise<void>;
        /**
          * The input field size. Possible values are: `"sm"`, `"md"`, `"lg"`. Defaults to `"md"`.
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * @default false
         */
        "skeleton": boolean;
        /**
          * The type of control to display. Possible values are: `"text"`, `"password"`, `"email"`, `"tel"`. Defaults to `"text"`.
          * @default 'text'
         */
        "type": 'text' | 'password' | 'email' | 'tel';
        /**
          * The input field value.
         */
        "value": string;
        /**
          * @default false
         */
        "warn": boolean;
        "warnText": string;
    }
    /**
     * @label Input URL
     * @name input-url
     * @description A specialized input field for URL validation.
     * @category Up coming
     * @tags input, form, url
     * @example <pc-input-url value="https://shivajivarma.com"></pc-input-url>
     */
    interface PcInputUrl {
        /**
          * Set the amount of time, in milliseconds, to wait to trigger the `valueChange` event after each keystroke.
          * @default 300
         */
        "debounce": number;
        /**
          * If true, the user cannot interact with the input. Defaults to `false`.
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "editing": boolean;
        /**
          * Get the component's unique ID
         */
        "getComponentId": () => Promise<string>;
        "label": string;
        /**
          * The input field name.
          * @default `pc-input-url-${this.gid}`
         */
        "name": string;
        /**
          * The input field placeholder.
         */
        "placeholder": string;
        /**
          * If true, required icon is show. Defaults to `false`.
          * @default false
         */
        "required": boolean;
        /**
          * Sets blur on the native `input`. Use this method instead of the global `input.blur()`.
         */
        "setBlur": () => Promise<void>;
        /**
          * Sets focus on the native `input`. Use this method instead of the global `input.focus()`.
         */
        "setFocus": () => Promise<void>;
        /**
          * The input field size. Possible values are: `"sm"`, `"md"`, `"lg"`. Defaults to `"md"`.
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * @default false
         */
        "skeleton": boolean;
        /**
          * The input field value.
         */
        "value": string;
    }
    /**
     * @label Modal
     * @name modal
     * @description Modals are used to display content in a layer above the app.
     * @category Informational
     * @subcategory Modal
     * @tags controls
     * @img /assets/img/modal.webp
     * @imgDark /assets/img/modal-dark.webp
     */
    interface PcModal {
        "heading": string;
        /**
          * @default false
         */
        "hideClose": boolean;
        /**
          * Specify whether the Modal is managed by the parent component
          * @default false
         */
        "managed": boolean;
        /**
          * Specify whether the Modal is currently open
          * @default false
         */
        "open": boolean;
        /**
          * @default false
         */
        "showLoader": boolean;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        "subheading": string;
    }
    /**
     * @label Modal Content
     * @name modal-content
     * @description The Modal Content component is used to display the content within a modal.
     * @category Informational
     * @subcategory Modal
     * @childComponent true
     */
    interface PcModalContent {
        /**
          * @default 'default'
         */
        "type": 'text' | 'borderless' | 'default';
    }
    /**
     * @label Notification Manager
     * @name notification-manager
     * @description The Notification Manager handles the organization and display of notifications within the application.
     * @category Informational
     * @tags notification
     * @img /assets/img/notification-manager.webp
     * @imgDark /assets/img/notification-manager-dark.webp
     */
    interface PcNotificationManager {
        /**
          * @default 'global'
         */
        "name": string;
        /**
          * @default 'bottom-right'
         */
        "position": | 'top-right'
    | 'top-left'
    | 'bottom-right'
    | 'bottom-left';
    }
    /**
     * @label Popover
     * @name popover
     * @description The Popover component is used to display additional information.
     * @category Informational
     * @subcategory Popover
     * @img /assets/img/dropdown.webp
     * @imgDark /assets/img/dropdown-dark.webp
     */
    interface PcPopover {
        /**
          * Time in milliseconds to wait before hiding the popover when the trigger is set to `"hover"`.
          * @default 300
         */
        "dismissTimeout": number;
        /**
          * Hides the popover. This method is useful when the trigger is set to `"manual"`.
         */
        "hide": () => Promise<void>;
        /**
          * The offset of the popover relative to the trigger element. This value is used to adjust the position of the popover along the axis of the trigger element.
          * @default 4
         */
        "offset": number;
        /**
          * Determines whether the popover is open.
          * @default false
         */
        "open": boolean;
        /**
          * Time in milliseconds to wait before showing the popover when the trigger is set to `"hover"`.
          * @default 200
         */
        "openTimeout": number;
        /**
          * The placement of the popover relative to the trigger element. Possible values are: - `"top"`: The popover is placed above the trigger element. - `"top-start"`: The popover is placed above the trigger element, aligned to the start. - `"top-end"`: The popover is placed above the trigger element, aligned to the end. - `"right"`: The popover is placed to the right of the trigger element. - `"right-start"`: The popover is placed to the right of the trigger element, aligned to the start. - `"right-end"`: The popover is placed to the right of the trigger element, aligned to the end. - `"bottom"`: The popover is placed below the trigger element. - `"bottom-start"`: The popover is placed below the trigger element, aligned to the start. - `"bottom-end"`: The popover is placed below the trigger element, aligned to the end. - `"left"`: The popover is placed to the left of the trigger element. - `"left-start"`: The popover is placed to the left of the trigger element, aligned to the start. - `"left-end"`: The popover is placed to the left of the trigger element, aligned to the end.
         */
        "placements": string;
        /**
          * Shows the popover. This method is particularly useful when the trigger mode is set to `"manual"`. It allows for programmatic control over the visibility of the popover, making it visible regardless of the trigger mode. Optionally, a target HTMLElement can be provided to dynamically set the trigger element for the popover.
         */
        "show": (target?: HTMLElement) => Promise<void>;
        /**
          * The tip of the popover. Possible values are: - `"caret"`: A triangle tip. - `"tab"`: A tab tip. - `"none"`: No tip.
          * @default 'caret'
         */
        "tip": 'caret' | 'tab' | 'none';
        /**
          * Determines how the popover is triggered. Possible values are: - `"click"`: The popover is shown or hidden when the trigger element is clicked. - `"hover"`: The popover is shown when the mouse hovers over the trigger element and hidden when it leaves. - `"manual"`: The visibility of the popover must be manually controlled through the `open` property.
          * @default 'hover'
         */
        "trigger": 'click' | 'hover' | 'manual';
    }
    /**
     * @label Popover Content
     * @name popover-content
     * @description The PopoverContent component is used to display additional information.
     * @category Informational
     * @subcategory Popover
     * @childComponent true
     */
    interface PcPopoverContent {
    }
}
export interface GoatHtmlEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGoatHtmlEditorElement;
}
export interface PcDropdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPcDropdownElement;
}
export interface PcInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPcInputElement;
}
export interface PcInputUrlCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPcInputUrlElement;
}
export interface PcModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPcModalElement;
}
export interface PcPopoverCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPcPopoverElement;
}
declare global {
    interface HTMLGoatHeaderActionElement extends Components.GoatHeaderAction, HTMLStencilElement {
    }
    var HTMLGoatHeaderActionElement: {
        prototype: HTMLGoatHeaderActionElement;
        new (): HTMLGoatHeaderActionElement;
    };
    interface HTMLGoatHeaderBrandElement extends Components.GoatHeaderBrand, HTMLStencilElement {
    }
    var HTMLGoatHeaderBrandElement: {
        prototype: HTMLGoatHeaderBrandElement;
        new (): HTMLGoatHeaderBrandElement;
    };
    interface HTMLGoatHtmlEditorElementEventMap {
        "goat-html-editor--change": any;
        "goat-html-editor--search": any;
    }
    /**
     * @label HTML Editor
     * @name html-editor
     * @description HTML Editor component is a WYSIWYG editor that allows users to edit HTML content.
     * @category Form Inputs
     * @tags input, form
     * @img /assets/img/html-editor.webp
     * @imgDark /assets/img/html-editor-dark.webp
     */
    interface HTMLGoatHtmlEditorElement extends Components.GoatHtmlEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGoatHtmlEditorElementEventMap>(type: K, listener: (this: HTMLGoatHtmlEditorElement, ev: GoatHtmlEditorCustomEvent<HTMLGoatHtmlEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGoatHtmlEditorElementEventMap>(type: K, listener: (this: HTMLGoatHtmlEditorElement, ev: GoatHtmlEditorCustomEvent<HTMLGoatHtmlEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGoatHtmlEditorElement: {
        prototype: HTMLGoatHtmlEditorElement;
        new (): HTMLGoatHtmlEditorElement;
    };
    /**
     * @label Canvas
     * @name canvas
     * @category Up coming
     * @description Canvas for drawing lines and shapes on.
     * @img /assets/img/canvas.webp
     */
    interface HTMLPcCanvasElement extends Components.PcCanvas, HTMLStencilElement {
    }
    var HTMLPcCanvasElement: {
        prototype: HTMLPcCanvasElement;
        new (): HTMLPcCanvasElement;
    };
    interface HTMLPcDropdownElementEventMap {
        "pc-dropdown--item-click": any;
        "pc-dropdown--open": any;
        "pc-dropdown--close": any;
    }
    /**
     * @label Dropdown
     * @name dropdown
     * @description Enables native inputs to be used within a Form field.
     * @category Navigation
     * @subcategory Dropdown
     * @img /assets/img/dropdown.webp
     * @imgDark /assets/img/dropdown-dark.webp
     */
    interface HTMLPcDropdownElement extends Components.PcDropdown, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPcDropdownElementEventMap>(type: K, listener: (this: HTMLPcDropdownElement, ev: PcDropdownCustomEvent<HTMLPcDropdownElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPcDropdownElementEventMap>(type: K, listener: (this: HTMLPcDropdownElement, ev: PcDropdownCustomEvent<HTMLPcDropdownElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPcDropdownElement: {
        prototype: HTMLPcDropdownElement;
        new (): HTMLPcDropdownElement;
    };
    /**
     * @label Dropdown Menu
     * @name dropdown-menu
     * @description The Dropdown Menu component is used to display a list of options.
     * @category Navigation
     * @subcategory Dropdown
     * @childComponent true
     */
    interface HTMLPcDropdownMenuElement extends Components.PcDropdownMenu, HTMLStencilElement {
    }
    var HTMLPcDropdownMenuElement: {
        prototype: HTMLPcDropdownMenuElement;
        new (): HTMLPcDropdownMenuElement;
    };
    /**
     * @label Flow Designer
     * @name flow-designer
     * @category Up coming
     * @description Flow Designer is a component that allows users to create and edit flows.
     * @img /assets/img/flow-designer.webp
     */
    interface HTMLPcFlowDesignerElement extends Components.PcFlowDesigner, HTMLStencilElement {
    }
    var HTMLPcFlowDesignerElement: {
        prototype: HTMLPcFlowDesignerElement;
        new (): HTMLPcFlowDesignerElement;
    };
    /**
     * @label Form Control
     * @name form-control
     * @description The Form Control component adds a label and caption for its child control.
     * @category Form Inputs
     * @tags form
     * @example <pc-form-control label='Full Name' required>
     * <pc-input type='text'></pc-input>
     * </pc-form-control>
     */
    interface HTMLPcFormControlElement extends Components.PcFormControl, HTMLStencilElement {
    }
    var HTMLPcFormControlElement: {
        prototype: HTMLPcFormControlElement;
        new (): HTMLPcFormControlElement;
    };
    /**
     * @label Header
     * @name header
     * @description Header component is used to display a header with a brand, navigation, and actions.
     * @category Navigation
     * @img /assets/img/header.webp
     * @imgDark /assets/img/header-dark.webp
     */
    interface HTMLPcHeaderElement extends Components.PcHeader, HTMLStencilElement {
    }
    var HTMLPcHeaderElement: {
        prototype: HTMLPcHeaderElement;
        new (): HTMLPcHeaderElement;
    };
    interface HTMLPcInputElementEventMap {
        "pc-input--input": any;
        "pc-input--change": any;
        "pc-input--blur": any;
        "pc-input--focus": any;
    }
    /**
     * @label Input
     * @name input
     * @description Enables native inputs to be used within a Form field.
     * @category Form Inputs
     * @tags input, form
     * @example <pc-input placeholder="Enter your name"></pc-input>
     */
    interface HTMLPcInputElement extends Components.PcInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPcInputElementEventMap>(type: K, listener: (this: HTMLPcInputElement, ev: PcInputCustomEvent<HTMLPcInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPcInputElementEventMap>(type: K, listener: (this: HTMLPcInputElement, ev: PcInputCustomEvent<HTMLPcInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPcInputElement: {
        prototype: HTMLPcInputElement;
        new (): HTMLPcInputElement;
    };
    interface HTMLPcInputUrlElementEventMap {
        "valueChange": string;
        "inputInvalid": boolean;
    }
    /**
     * @label Input URL
     * @name input-url
     * @description A specialized input field for URL validation.
     * @category Up coming
     * @tags input, form, url
     * @example <pc-input-url value="https://shivajivarma.com"></pc-input-url>
     */
    interface HTMLPcInputUrlElement extends Components.PcInputUrl, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPcInputUrlElementEventMap>(type: K, listener: (this: HTMLPcInputUrlElement, ev: PcInputUrlCustomEvent<HTMLPcInputUrlElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPcInputUrlElementEventMap>(type: K, listener: (this: HTMLPcInputUrlElement, ev: PcInputUrlCustomEvent<HTMLPcInputUrlElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPcInputUrlElement: {
        prototype: HTMLPcInputUrlElement;
        new (): HTMLPcInputUrlElement;
    };
    interface HTMLPcModalElementEventMap {
        "pc-modal--close": any;
    }
    /**
     * @label Modal
     * @name modal
     * @description Modals are used to display content in a layer above the app.
     * @category Informational
     * @subcategory Modal
     * @tags controls
     * @img /assets/img/modal.webp
     * @imgDark /assets/img/modal-dark.webp
     */
    interface HTMLPcModalElement extends Components.PcModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPcModalElementEventMap>(type: K, listener: (this: HTMLPcModalElement, ev: PcModalCustomEvent<HTMLPcModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPcModalElementEventMap>(type: K, listener: (this: HTMLPcModalElement, ev: PcModalCustomEvent<HTMLPcModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPcModalElement: {
        prototype: HTMLPcModalElement;
        new (): HTMLPcModalElement;
    };
    /**
     * @label Modal Content
     * @name modal-content
     * @description The Modal Content component is used to display the content within a modal.
     * @category Informational
     * @subcategory Modal
     * @childComponent true
     */
    interface HTMLPcModalContentElement extends Components.PcModalContent, HTMLStencilElement {
    }
    var HTMLPcModalContentElement: {
        prototype: HTMLPcModalContentElement;
        new (): HTMLPcModalContentElement;
    };
    /**
     * @label Notification Manager
     * @name notification-manager
     * @description The Notification Manager handles the organization and display of notifications within the application.
     * @category Informational
     * @tags notification
     * @img /assets/img/notification-manager.webp
     * @imgDark /assets/img/notification-manager-dark.webp
     */
    interface HTMLPcNotificationManagerElement extends Components.PcNotificationManager, HTMLStencilElement {
    }
    var HTMLPcNotificationManagerElement: {
        prototype: HTMLPcNotificationManagerElement;
        new (): HTMLPcNotificationManagerElement;
    };
    interface HTMLPcPopoverElementEventMap {
        "pc-popover--open": any;
        "pc-popover--close": any;
    }
    /**
     * @label Popover
     * @name popover
     * @description The Popover component is used to display additional information.
     * @category Informational
     * @subcategory Popover
     * @img /assets/img/dropdown.webp
     * @imgDark /assets/img/dropdown-dark.webp
     */
    interface HTMLPcPopoverElement extends Components.PcPopover, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPcPopoverElementEventMap>(type: K, listener: (this: HTMLPcPopoverElement, ev: PcPopoverCustomEvent<HTMLPcPopoverElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPcPopoverElementEventMap>(type: K, listener: (this: HTMLPcPopoverElement, ev: PcPopoverCustomEvent<HTMLPcPopoverElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPcPopoverElement: {
        prototype: HTMLPcPopoverElement;
        new (): HTMLPcPopoverElement;
    };
    /**
     * @label Popover Content
     * @name popover-content
     * @description The PopoverContent component is used to display additional information.
     * @category Informational
     * @subcategory Popover
     * @childComponent true
     */
    interface HTMLPcPopoverContentElement extends Components.PcPopoverContent, HTMLStencilElement {
    }
    var HTMLPcPopoverContentElement: {
        prototype: HTMLPcPopoverContentElement;
        new (): HTMLPcPopoverContentElement;
    };
    interface HTMLElementTagNameMap {
        "goat-header-action": HTMLGoatHeaderActionElement;
        "goat-header-brand": HTMLGoatHeaderBrandElement;
        "goat-html-editor": HTMLGoatHtmlEditorElement;
        "pc-canvas": HTMLPcCanvasElement;
        "pc-dropdown": HTMLPcDropdownElement;
        "pc-dropdown-menu": HTMLPcDropdownMenuElement;
        "pc-flow-designer": HTMLPcFlowDesignerElement;
        "pc-form-control": HTMLPcFormControlElement;
        "pc-header": HTMLPcHeaderElement;
        "pc-input": HTMLPcInputElement;
        "pc-input-url": HTMLPcInputUrlElement;
        "pc-modal": HTMLPcModalElement;
        "pc-modal-content": HTMLPcModalContentElement;
        "pc-notification-manager": HTMLPcNotificationManagerElement;
        "pc-popover": HTMLPcPopoverElement;
        "pc-popover-content": HTMLPcPopoverContentElement;
    }
}
declare namespace LocalJSX {
    interface GoatHeaderAction {
        /**
          * @default '_self'
         */
        "badge"?: string;
        /**
          * @default {}
         */
        "configAria"?: any;
        /**
          * Hyperlink to navigate to on click.
         */
        "href"?: string;
        /**
          * Icon which will displayed on button. Possible values are icon names.
         */
        "icon"?: string;
        /**
          * IconButton size. Possible values are `"sm"`, `"md"`, `"lg"`, `"xl"`, `"xxl"`, `"none"`. Defaults to `"md"`.
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg' | 'xl' | 'xxl' | 'none';
        /**
          * Sets or retrieves the window or frame at which to target content.
          * @default '_self'
         */
        "target"?: string;
    }
    interface GoatHeaderBrand {
        /**
          * @default '#'
         */
        "href"?: string;
        "logo"?: string;
        "name"?: string;
        "subTitle"?: string;
    }
    /**
     * @label HTML Editor
     * @name html-editor
     * @description HTML Editor component is a WYSIWYG editor that allows users to edit HTML content.
     * @category Form Inputs
     * @tags input, form
     * @img /assets/img/html-editor.webp
     * @imgDark /assets/img/html-editor-dark.webp
     */
    interface GoatHtmlEditor {
        /**
          * Set the amount of time, in milliseconds, to wait to trigger the `onChange` event after each keystroke.
          * @default 250
         */
        "debounce"?: number;
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
          * @default false
         */
        "disabled"?: boolean;
        "layer"?: 'background' | '01' | '02';
        /**
          * @default 'on'
         */
        "lineNumbers"?: 'off' | 'on';
        /**
          * @default []
         */
        "mentions"?: { label: string; value: string }[];
        /**
          * @default 'contains'
         */
        "mentionsSearch"?: 'contains' | 'managed';
        /**
          * The input field name.
          * @default `pc-input-${this.gid}`
         */
        "name"?: string;
        /**
          * Emitted when the value has changed..
         */
        "onGoat-html-editor--change"?: (event: GoatHtmlEditorCustomEvent<any>) => void;
        /**
          * Emitted when a keyboard input occurred.
         */
        "onGoat-html-editor--search"?: (event: GoatHtmlEditorCustomEvent<any>) => void;
        /**
          * The input field placeholder.
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * If true, required icon is show. Defaults to `false`.
          * @default false
         */
        "required"?: boolean;
        /**
          * @default true
         */
        "showSuggestionCharacter"?: boolean;
        /**
          * @default true
         */
        "showToolbar"?: boolean;
        /**
          * @default '@'
         */
        "suggestionCharacter"?: string;
        /**
          * @default 'vs-light'
         */
        "theme"?: 'vs-light' | 'vs-dark';
        /**
          * The input field value.
         */
        "value"?: string;
    }
    /**
     * @label Canvas
     * @name canvas
     * @category Up coming
     * @description Canvas for drawing lines and shapes on.
     * @img /assets/img/canvas.webp
     */
    interface PcCanvas {
        /**
          * @default 1
         */
        "padding"?: number;
        /**
          * @default []
         */
        "shapes"?: any[];
        "viewbox"?: string;
        /**
          * @default 1
         */
        "zoom"?: number;
    }
    /**
     * @label Dropdown
     * @name dropdown
     * @description Enables native inputs to be used within a Form field.
     * @category Navigation
     * @subcategory Dropdown
     * @img /assets/img/dropdown.webp
     * @imgDark /assets/img/dropdown-dark.webp
     */
    interface PcDropdown {
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "managed"?: boolean;
        /**
          * Emitted when the dropdown is closed.
         */
        "onPc-dropdown--close"?: (event: PcDropdownCustomEvent<any>) => void;
        "onPc-dropdown--item-click"?: (event: PcDropdownCustomEvent<any>) => void;
        /**
          * Emitted when the dropdown is opened.
         */
        "onPc-dropdown--open"?: (event: PcDropdownCustomEvent<any>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * @default 'bottom-start,top-start,bottom-end,top-end'
         */
        "placements"?: string;
        /**
          * @default 'click'
         */
        "trigger"?: 'click' | 'hover' | 'manual';
    }
    /**
     * @label Dropdown Menu
     * @name dropdown-menu
     * @description The Dropdown Menu component is used to display a list of options.
     * @category Navigation
     * @subcategory Dropdown
     * @childComponent true
     */
    interface PcDropdownMenu {
    }
    /**
     * @label Flow Designer
     * @name flow-designer
     * @category Up coming
     * @description Flow Designer is a component that allows users to create and edit flows.
     * @img /assets/img/flow-designer.webp
     */
    interface PcFlowDesigner {
        /**
          * @default 16
         */
        "blockSize"?: number;
        /**
          * @default []
         */
        "data"?: any[];
        /**
          * @default false
         */
        "disabled"?: boolean;
    }
    /**
     * @label Form Control
     * @name form-control
     * @description The Form Control component adds a label and caption for its child control.
     * @category Form Inputs
     * @tags form
     * @example <pc-form-control label='Full Name' required>
     * <pc-input type='text'></pc-input>
     * </pc-form-control>
     */
    interface PcFormControl {
        "helperText"?: string;
        /**
          * @default false
         */
        "inline"?: boolean;
        /**
          * @default false
         */
        "invalid"?: boolean;
        "invalidText"?: string;
        "label"?: string;
        /**
          * Whether the form control is required.
          * @default false
         */
        "required"?: boolean;
        /**
          * @default false
         */
        "skeleton"?: boolean;
        /**
          * @default false
         */
        "warn"?: boolean;
        "warnText"?: string;
    }
    /**
     * @label Header
     * @name header
     * @description Header component is used to display a header with a brand, navigation, and actions.
     * @category Navigation
     * @img /assets/img/header.webp
     * @imgDark /assets/img/header-dark.webp
     */
    interface PcHeader {
        /**
          * Defines the primary color of the header. This can be set to predefined color names to apply specific color themes.
          * @default 'black'
         */
        "color"?: | 'primary'
    | 'secondary'
    | 'success'
    | 'danger'
    | 'warning'
    | 'white'
    | 'black'
    | string;
        /**
          * Color variant for dark mode, applicable when [data-theme="dark"] is set.
         */
        "darkModeColor"?: | 'primary'
    | 'secondary'
    | 'success'
    | 'danger'
    | 'warning'
    | 'white'
    | 'black'
    | string;
        /**
          * @default false
         */
        "float"?: boolean;
    }
    /**
     * @label Input
     * @name input
     * @description Enables native inputs to be used within a Form field.
     * @category Form Inputs
     * @tags input, form
     * @example <pc-input placeholder="Enter your name"></pc-input>
     */
    interface PcInput {
        /**
          * Indicates whether the value of the control can be automatically completed by the browser.
          * @default 'off'
         */
        "autocomplete"?: 'on' | 'off';
        /**
          * @default {}
         */
        "configAria"?: any;
        /**
          * Set the amount of time, in milliseconds, to wait to trigger the `goatChange` event after each keystroke.
          * @default 300
         */
        "debounce"?: number;
        /**
          * If true, the user cannot interact with the button. Defaults to `false`.
          * @default false
         */
        "disabled"?: boolean;
        "helperText"?: string;
        /**
          * @default false
         */
        "inline"?: boolean;
        /**
          * @default false
         */
        "invalid"?: boolean;
        "invalidText"?: string;
        "label"?: string;
        /**
          * The input field name.
          * @default `pc-input-${this.gid}`
         */
        "name"?: string;
        /**
          * Emitted when the input loses focus.
         */
        "onPc-input--blur"?: (event: PcInputCustomEvent<any>) => void;
        /**
          * Emitted when the value has changed.
         */
        "onPc-input--change"?: (event: PcInputCustomEvent<any>) => void;
        /**
          * Emitted when the input has focus.
         */
        "onPc-input--focus"?: (event: PcInputCustomEvent<any>) => void;
        /**
          * Emitted when a keyboard input occurred.
         */
        "onPc-input--input"?: (event: PcInputCustomEvent<any>) => void;
        /**
          * The input field placeholder.
         */
        "placeholder"?: string;
        /**
          * If true, the user read the value cannot modify it. Defaults to `false`.
          * @default false
         */
        "readonly"?: boolean;
        /**
          * If true, required icon is show. Defaults to `false`.
          * @default false
         */
        "required"?: boolean;
        /**
          * The input field size. Possible values are: `"sm"`, `"md"`, `"lg"`. Defaults to `"md"`.
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * @default false
         */
        "skeleton"?: boolean;
        /**
          * The type of control to display. Possible values are: `"text"`, `"password"`, `"email"`, `"tel"`. Defaults to `"text"`.
          * @default 'text'
         */
        "type"?: 'text' | 'password' | 'email' | 'tel';
        /**
          * The input field value.
         */
        "value"?: string;
        /**
          * @default false
         */
        "warn"?: boolean;
        "warnText"?: string;
    }
    /**
     * @label Input URL
     * @name input-url
     * @description A specialized input field for URL validation.
     * @category Up coming
     * @tags input, form, url
     * @example <pc-input-url value="https://shivajivarma.com"></pc-input-url>
     */
    interface PcInputUrl {
        /**
          * Set the amount of time, in milliseconds, to wait to trigger the `valueChange` event after each keystroke.
          * @default 300
         */
        "debounce"?: number;
        /**
          * If true, the user cannot interact with the input. Defaults to `false`.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "editing"?: boolean;
        "label"?: string;
        /**
          * The input field name.
          * @default `pc-input-url-${this.gid}`
         */
        "name"?: string;
        /**
          * Emitted when the URL input is invalid.
         */
        "onInputInvalid"?: (event: PcInputUrlCustomEvent<boolean>) => void;
        /**
          * Emitted when a keyboard input occurred.
         */
        "onValueChange"?: (event: PcInputUrlCustomEvent<string>) => void;
        /**
          * The input field placeholder.
         */
        "placeholder"?: string;
        /**
          * If true, required icon is show. Defaults to `false`.
          * @default false
         */
        "required"?: boolean;
        /**
          * The input field size. Possible values are: `"sm"`, `"md"`, `"lg"`. Defaults to `"md"`.
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * @default false
         */
        "skeleton"?: boolean;
        /**
          * The input field value.
         */
        "value"?: string;
    }
    /**
     * @label Modal
     * @name modal
     * @description Modals are used to display content in a layer above the app.
     * @category Informational
     * @subcategory Modal
     * @tags controls
     * @img /assets/img/modal.webp
     * @imgDark /assets/img/modal-dark.webp
     */
    interface PcModal {
        "heading"?: string;
        /**
          * @default false
         */
        "hideClose"?: boolean;
        /**
          * Specify whether the Modal is managed by the parent component
          * @default false
         */
        "managed"?: boolean;
        /**
          * On click of button, a CustomEvent 'pc-modal--close' will be triggered.
         */
        "onPc-modal--close"?: (event: PcModalCustomEvent<any>) => void;
        /**
          * Specify whether the Modal is currently open
          * @default false
         */
        "open"?: boolean;
        /**
          * @default false
         */
        "showLoader"?: boolean;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        "subheading"?: string;
    }
    /**
     * @label Modal Content
     * @name modal-content
     * @description The Modal Content component is used to display the content within a modal.
     * @category Informational
     * @subcategory Modal
     * @childComponent true
     */
    interface PcModalContent {
        /**
          * @default 'default'
         */
        "type"?: 'text' | 'borderless' | 'default';
    }
    /**
     * @label Notification Manager
     * @name notification-manager
     * @description The Notification Manager handles the organization and display of notifications within the application.
     * @category Informational
     * @tags notification
     * @img /assets/img/notification-manager.webp
     * @imgDark /assets/img/notification-manager-dark.webp
     */
    interface PcNotificationManager {
        /**
          * @default 'global'
         */
        "name"?: string;
        /**
          * @default 'bottom-right'
         */
        "position"?: | 'top-right'
    | 'top-left'
    | 'bottom-right'
    | 'bottom-left';
    }
    /**
     * @label Popover
     * @name popover
     * @description The Popover component is used to display additional information.
     * @category Informational
     * @subcategory Popover
     * @img /assets/img/dropdown.webp
     * @imgDark /assets/img/dropdown-dark.webp
     */
    interface PcPopover {
        /**
          * Time in milliseconds to wait before hiding the popover when the trigger is set to `"hover"`.
          * @default 300
         */
        "dismissTimeout"?: number;
        /**
          * The offset of the popover relative to the trigger element. This value is used to adjust the position of the popover along the axis of the trigger element.
          * @default 4
         */
        "offset"?: number;
        /**
          * Emitted when the popover is closed.
         */
        "onPc-popover--close"?: (event: PcPopoverCustomEvent<any>) => void;
        /**
          * Emitted when the popover is opened.
         */
        "onPc-popover--open"?: (event: PcPopoverCustomEvent<any>) => void;
        /**
          * Determines whether the popover is open.
          * @default false
         */
        "open"?: boolean;
        /**
          * Time in milliseconds to wait before showing the popover when the trigger is set to `"hover"`.
          * @default 200
         */
        "openTimeout"?: number;
        /**
          * The placement of the popover relative to the trigger element. Possible values are: - `"top"`: The popover is placed above the trigger element. - `"top-start"`: The popover is placed above the trigger element, aligned to the start. - `"top-end"`: The popover is placed above the trigger element, aligned to the end. - `"right"`: The popover is placed to the right of the trigger element. - `"right-start"`: The popover is placed to the right of the trigger element, aligned to the start. - `"right-end"`: The popover is placed to the right of the trigger element, aligned to the end. - `"bottom"`: The popover is placed below the trigger element. - `"bottom-start"`: The popover is placed below the trigger element, aligned to the start. - `"bottom-end"`: The popover is placed below the trigger element, aligned to the end. - `"left"`: The popover is placed to the left of the trigger element. - `"left-start"`: The popover is placed to the left of the trigger element, aligned to the start. - `"left-end"`: The popover is placed to the left of the trigger element, aligned to the end.
         */
        "placements"?: string;
        /**
          * The tip of the popover. Possible values are: - `"caret"`: A triangle tip. - `"tab"`: A tab tip. - `"none"`: No tip.
          * @default 'caret'
         */
        "tip"?: 'caret' | 'tab' | 'none';
        /**
          * Determines how the popover is triggered. Possible values are: - `"click"`: The popover is shown or hidden when the trigger element is clicked. - `"hover"`: The popover is shown when the mouse hovers over the trigger element and hidden when it leaves. - `"manual"`: The visibility of the popover must be manually controlled through the `open` property.
          * @default 'hover'
         */
        "trigger"?: 'click' | 'hover' | 'manual';
    }
    /**
     * @label Popover Content
     * @name popover-content
     * @description The PopoverContent component is used to display additional information.
     * @category Informational
     * @subcategory Popover
     * @childComponent true
     */
    interface PcPopoverContent {
    }
    interface IntrinsicElements {
        "goat-header-action": GoatHeaderAction;
        "goat-header-brand": GoatHeaderBrand;
        "goat-html-editor": GoatHtmlEditor;
        "pc-canvas": PcCanvas;
        "pc-dropdown": PcDropdown;
        "pc-dropdown-menu": PcDropdownMenu;
        "pc-flow-designer": PcFlowDesigner;
        "pc-form-control": PcFormControl;
        "pc-header": PcHeader;
        "pc-input": PcInput;
        "pc-input-url": PcInputUrl;
        "pc-modal": PcModal;
        "pc-modal-content": PcModalContent;
        "pc-notification-manager": PcNotificationManager;
        "pc-popover": PcPopover;
        "pc-popover-content": PcPopoverContent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "goat-header-action": LocalJSX.GoatHeaderAction & JSXBase.HTMLAttributes<HTMLGoatHeaderActionElement>;
            "goat-header-brand": LocalJSX.GoatHeaderBrand & JSXBase.HTMLAttributes<HTMLGoatHeaderBrandElement>;
            /**
             * @label HTML Editor
             * @name html-editor
             * @description HTML Editor component is a WYSIWYG editor that allows users to edit HTML content.
             * @category Form Inputs
             * @tags input, form
             * @img /assets/img/html-editor.webp
             * @imgDark /assets/img/html-editor-dark.webp
             */
            "goat-html-editor": LocalJSX.GoatHtmlEditor & JSXBase.HTMLAttributes<HTMLGoatHtmlEditorElement>;
            /**
             * @label Canvas
             * @name canvas
             * @category Up coming
             * @description Canvas for drawing lines and shapes on.
             * @img /assets/img/canvas.webp
             */
            "pc-canvas": LocalJSX.PcCanvas & JSXBase.HTMLAttributes<HTMLPcCanvasElement>;
            /**
             * @label Dropdown
             * @name dropdown
             * @description Enables native inputs to be used within a Form field.
             * @category Navigation
             * @subcategory Dropdown
             * @img /assets/img/dropdown.webp
             * @imgDark /assets/img/dropdown-dark.webp
             */
            "pc-dropdown": LocalJSX.PcDropdown & JSXBase.HTMLAttributes<HTMLPcDropdownElement>;
            /**
             * @label Dropdown Menu
             * @name dropdown-menu
             * @description The Dropdown Menu component is used to display a list of options.
             * @category Navigation
             * @subcategory Dropdown
             * @childComponent true
             */
            "pc-dropdown-menu": LocalJSX.PcDropdownMenu & JSXBase.HTMLAttributes<HTMLPcDropdownMenuElement>;
            /**
             * @label Flow Designer
             * @name flow-designer
             * @category Up coming
             * @description Flow Designer is a component that allows users to create and edit flows.
             * @img /assets/img/flow-designer.webp
             */
            "pc-flow-designer": LocalJSX.PcFlowDesigner & JSXBase.HTMLAttributes<HTMLPcFlowDesignerElement>;
            /**
             * @label Form Control
             * @name form-control
             * @description The Form Control component adds a label and caption for its child control.
             * @category Form Inputs
             * @tags form
             * @example <pc-form-control label='Full Name' required>
             * <pc-input type='text'></pc-input>
             * </pc-form-control>
             */
            "pc-form-control": LocalJSX.PcFormControl & JSXBase.HTMLAttributes<HTMLPcFormControlElement>;
            /**
             * @label Header
             * @name header
             * @description Header component is used to display a header with a brand, navigation, and actions.
             * @category Navigation
             * @img /assets/img/header.webp
             * @imgDark /assets/img/header-dark.webp
             */
            "pc-header": LocalJSX.PcHeader & JSXBase.HTMLAttributes<HTMLPcHeaderElement>;
            /**
             * @label Input
             * @name input
             * @description Enables native inputs to be used within a Form field.
             * @category Form Inputs
             * @tags input, form
             * @example <pc-input placeholder="Enter your name"></pc-input>
             */
            "pc-input": LocalJSX.PcInput & JSXBase.HTMLAttributes<HTMLPcInputElement>;
            /**
             * @label Input URL
             * @name input-url
             * @description A specialized input field for URL validation.
             * @category Up coming
             * @tags input, form, url
             * @example <pc-input-url value="https://shivajivarma.com"></pc-input-url>
             */
            "pc-input-url": LocalJSX.PcInputUrl & JSXBase.HTMLAttributes<HTMLPcInputUrlElement>;
            /**
             * @label Modal
             * @name modal
             * @description Modals are used to display content in a layer above the app.
             * @category Informational
             * @subcategory Modal
             * @tags controls
             * @img /assets/img/modal.webp
             * @imgDark /assets/img/modal-dark.webp
             */
            "pc-modal": LocalJSX.PcModal & JSXBase.HTMLAttributes<HTMLPcModalElement>;
            /**
             * @label Modal Content
             * @name modal-content
             * @description The Modal Content component is used to display the content within a modal.
             * @category Informational
             * @subcategory Modal
             * @childComponent true
             */
            "pc-modal-content": LocalJSX.PcModalContent & JSXBase.HTMLAttributes<HTMLPcModalContentElement>;
            /**
             * @label Notification Manager
             * @name notification-manager
             * @description The Notification Manager handles the organization and display of notifications within the application.
             * @category Informational
             * @tags notification
             * @img /assets/img/notification-manager.webp
             * @imgDark /assets/img/notification-manager-dark.webp
             */
            "pc-notification-manager": LocalJSX.PcNotificationManager & JSXBase.HTMLAttributes<HTMLPcNotificationManagerElement>;
            /**
             * @label Popover
             * @name popover
             * @description The Popover component is used to display additional information.
             * @category Informational
             * @subcategory Popover
             * @img /assets/img/dropdown.webp
             * @imgDark /assets/img/dropdown-dark.webp
             */
            "pc-popover": LocalJSX.PcPopover & JSXBase.HTMLAttributes<HTMLPcPopoverElement>;
            /**
             * @label Popover Content
             * @name popover-content
             * @description The PopoverContent component is used to display additional information.
             * @category Informational
             * @subcategory Popover
             * @childComponent true
             */
            "pc-popover-content": LocalJSX.PcPopoverContent & JSXBase.HTMLAttributes<HTMLPcPopoverContentElement>;
        }
    }
}
