name: Build

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
      - 'releases/**'

permissions:
  id-token: write  # Required for OIDC
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC
      contents: write
      packages: write # Required to write packages

    strategy:
      matrix:
        node-version: [20.10.0]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Cache design-tokens node_modules
        id: cache-design-tokens
        uses: actions/cache@v3
        with:
          path: design-tokens/node_modules
          # This is the reliable way to generate a key based on your dependencies
          key: ${{ runner.os }}-design-tokens-${{ hashFiles('design-tokens/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-design-tokens-node-modules-

      - name: Cache components node_modules
        id: cache-components
        uses: actions/cache@v3
        with:
          path: components/node_modules
          # This is the reliable way to generate a key based on your dependencies
          key: ${{ runner.os }}-components-${{ hashFiles('components/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-components-node-modules-

      - name: npm install, build, and test
        run: |
          cd design-tokens
          npm ci
          npm run build
          npm run deploy

          cd ../components
          npm ci
          npm run build
          npm publish --access public  # Added access flag for safety
